version: '3.8'

services:
  database:
    container_name: cetus-database
    image: postgres
    restart: always
    ports:
      - "6060:5432"
    environment:
      PGDATA: ./data
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: cetus-app
    volumes:
      - ./data:/var/lib/postgresql/data
  redis:
    container_name: cetus-cache
    image: redis
    restart: always
    ports:
      - "6070:6379"
  app:
    container_name: cetus-app
    build: .
    restart: always
    ports:
      - "8000:3000"
    environment:
      DATABASE_URL: postgres://user:password@database:6060/cetus-app
      REDIS_URL: redis://redis:6070
      SESSION_SECRET: ${SESSION_SECRET}
    depends_on:
      - database
      - redis
